### ISSUE TITLE
audio is not playing in the viewer

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-collection-viewer#10]
The screen ends with 'Loading media... please wait.'. Also reported by other users. In both the test viewer and the current viewer. I'm not sure if this is a viewer issue or for Terem to deal with, but the media plays fine in NABU.

**Comment by MLR-au** [comment]
Item / Collection? Which media file? Might be an format unsupported by the viewer (it has a whitelist) or something else.

**Comment by nthieberger** [comment]
I think this was actually an issue related to a user not being logged in but trying to play media. Hence the need for a message to the user telling them they need to log in

**Comment by MLR-au** [comment]
Closed as a duplicate of #11
