### ISSUE TITLE
no thumbnail navigation in test-viewer

### ISSUE THREAD

**Issue by LindaBarwick** [MLR-au/pdsc-collection-viewer#4]
in old viewer, doubleclicking on thumbnail navigated to that image. In test-viewer, no navigation from thumbnails seems to be possible (testing on item LB2/92PIX01) (firefox 45.0.2 / Mac OSX 10.11.4, also Safari Version 9.1 (11601.5.17.1))

**Comment by MLR-au** [comment]
This is really odd. That functionality works in development but seems to break when I package up the application for deployment. Looking in to it now.
