### ISSUE TITLE
Media needs to play from anywhere, not just from the beginning

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-collection-viewer#7]
This is critical, especially for timed segments, but also for any media slider to play from the point at which it is selected.

**Comment by MLR-au** [comment]
I think this is problem with Nabu rather than the viewer so I've logged a request in the Nabu issue tracker: https://github.com/nabu-catalog/nabu/issues/584. Could you please assign to the relevant person and prioritise?

**Comment by nthieberger** [comment]
I already have an issue with them too.

**Comment by MLR-au** [comment]
This was a backend issue and it's been fixed.
