### ISSUE TITLE
Window jumps to segment but does not allow user to see the controller

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-collection-viewer#8]
When it is playing, the window moves down to the text, but then it is not possible to pause the player as the controller is not visible. Can the play button at each segment switch to a pause button when it is playing?

**Comment by MLR-au** [comment]
This is sort of related to #9 given that the viewer can now display multiple transcriptions are once. When more than one is displayed the total vertical space required is greater than the browser vertical height so the scroll event on the transcription brings the highlighted transcription to the top of the page.

This could be mitigated by the proposal in #9 where the user is allowed to display only one transcription at a time.

**Comment by MLR-au** [comment]
New version pushed to testing with a selector to show only one of transcription or interlinear. This should mitigate this issue. See: http://catalog.paradisec.org.au/test-viewer/#/NT1/98007/NT1-98007-98007A
