### ISSUE TITLE
Scrolling is not working in the viewer

### ISSUE THREAD

**Issue by nthieberger** [MLR-au/pdsc-collection-viewer#9]
Text highlighting and scrolling is not working

**Comment by MLR-au** [comment]
Ok - I found the code that's been removed but there's an issue. Given that an item can have both a transcription and interlinear text I can't actually tell which one to scroll. We need to think of a way to show only one or the other (either the transcription or the interlinear) and enable scrolling them.

**Comment by MLR-au** [comment]
@nthieberger Any ideas on how to tackle this?

The issue stems from the fact that there can be multiple transcriptions on the page at once. Playing the media then results in a situation where the app doesn't know which transcription to scroll.

Perhaps it should be rejigged to show only the list of transcriptions available (without actually drawing them). The user would then need to select one to display (and only be able to show one at a time) that would be scrolled as the media plays.

Thoughts?

**Comment by nthieberger** [comment]
Yes, showing only one is fine, and having it close when another is selected is ok too

**Comment by MLR-au** [comment]
New version with a selector to choose which to display pushed to testing. See http://catalog.paradisec.org.au/test-viewer/#/NT1/98007/NT1-98007-98007A
